name: Release Workflow

on:
  push:
    branches:
      - 'upm' 
    tags:
      - '*'
      
permissions:
  contents: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
              ref : 'upm'
        
      - name: Release
        uses: softprops/action-gh-release@v1
