name: Release Workflow

on:
  push: 
    tags:
      - '*'
    branches:
      -'upm'
      
permissions:
  contents: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Release
        uses: softprops/action-gh-release@v1
