name: Release Workflow

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref : 'upm'

      - name: Switch Branch
        id: switch_branch
        run: gh pr checkout upm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        
      - name: Create Release
        id: create_release
        run: gh release create ${{ github.ref }} --target upm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
